//Collage:
const ACTION_CHANGE_USER_INPUT = "ACTION_CHANGE_USER_INPUT";
const ACTION_CHANGE_IMAGE = "ACTION_CHANGE_IMAGE";
const ACTION_CHANGE_TITTLE = "ACTION_CHANGE_TITTLE";
const ACTION_CHANGE_DESCRIPTION = "ACTION_CHANGE_DESCRIPTION";
const ACTION_CHANGE_COLLAGE = "ACTION_CHANGE_COLLAGE";

//Login:
const ACTION_CHANGE_AUTHORISED = "ACTION_CHANGE_AUTHORISED";
const ACTION_CHANGE_USERNAME = "ACTION_CHANGE_USERNAME";
const ACTION_CHANGE_PASSWORD = "ACTION_CHANGE_PASSWORD";

//Navigation:
const ACTION_CHANGE_NAVIGATION_VISIBILITY =
  "ACTION_CHANGE_NAVIGATION_VISIBILITY";

export {
  ACTION_CHANGE_AUTHORISED,
  ACTION_CHANGE_COLLAGE,
  ACTION_CHANGE_DESCRIPTION,
  ACTION_CHANGE_IMAGE,
  ACTION_CHANGE_NAVIGATION_VISIBILITY,
  ACTION_CHANGE_PASSWORD,
  ACTION_CHANGE_TITTLE,
  ACTION_CHANGE_USER_INPUT,
  ACTION_CHANGE_USERNAME,
};
